### PR TITLE
Updates to Gnome 45

### PR DESCRIPTION
**Pull request by acristoffers**
This makes the extension work on Gnome 45, fixing #6.

I'm sorry about the very messy diff, but it seems that my LSP formatter changed the file a bit too much, giving the impression that a lot changed when only a few modifications were needed.

I'll list the modification to ease you code review:

- Changed all imports, because now they follow the module format
- No more ExtensionUtils, so no import for that and `getSettings` comes from the object (be it extension or preference)
- Both extension and preferences are now objects extending a base class and exported with `export default`
- The `row_extra` variable now needs the `const` (or `var` or `let`) before it, the engine no longer accepts the fact that it is not defined at the point of assignment

### CODE REVIEW

**Comment by acristoffers** [comment]
Oh, it was actually not the formatter at all, it was git that did the diff in a weird way. It did not understand that the function became a method (gaining a level of indentation) and so it broke it into 3 different diff sections :P

**Comment by osamuaoki** [comment]
Thanks for the great work.  Looks great.

(I am following your branch with `git remote update ...` not via github GUI)

Is this backward compatible to which GNOME?

**Comment by acristoffers** [comment]
Unfortunately not. As far as I know the GNOME team did not give a way to make extensions compatible with both pre- and post-version 45 :/ I also remember reading somewhere that it was in fact a breaking change, but I don't remember where to link here.

**Comment by osamuaoki** [comment]
I tried your on my GNOME43.  It doesn't work.  I need to know which one works for 44 to update uploaded packages.

**Comment by acristoffers** [comment]
Only 45. GNOME did not provide a way to make extensions backwards-compatible.

**Comment by acristoffers** [comment]
```markdown
# What does this mean for extensions?

Extensions that target older GNOME versions will not work in GNOME 45. Likewise, extensions that are adapted to work with GNOME 45 will not work in older versions.
```

https://blogs.gnome.org/shell-dev/2023/09/02/extensions-in-gnome-45/

**Comment by osamuaoki** [comment]
Thanks for guiding me.  I merged and added some doc updates.

FYI: version isn't needed for git repo.  Zip file upload to GNOME extension site automatically add it :-)

Have you considered to update test-keys sub-directory content.  This is needed to Debug user problem with odd keyboards.

**Comment by acristoffers** [comment]
Thanks, I didn't know.

I didn't see there was another extension there. I updated it too an pushed a commit to my fork. Since you're not using GitHub to merge I'll not open another pull-request, you can just grab it from same place you got this one. I tested it to make sure it runs and its preference pane opens, and that clicking the button and performing an unassigned shortcut changed the text. It seems to be working, but it was by no means an exhaustive test.

**Comment by osamuaoki** [comment]
I merged everything.  (Since I made mistake on trivial edit, I fixed json by removing extra-comma.)

I uploaded it to GNOME extension site.  If you find any issue, please open new issue/pull-request.

Thanks in advance for your help.

**Comment by osamuaoki** [comment]
I have uploaded to https://extensions.gnome.org/extension/6066/shortcuts-to-activate-input-methods/

If you have problem downloading this from there, let me know

**Comment by acristoffers** [comment]
It's not available for download yet. Was it reviewed already? I sent an extension this weekend but it wasn't reviewed yet...

**Comment by osamuaoki** [comment]
True.  It just approved.  So you should see it now.

**Comment by acristoffers** [comment]
Yep, I updated a few minutes ago. It seems to be working just fine for me, no problem.

**Comment by osamuaoki** [comment]
Great.

**Pull request merged**
